@extends('layouts.app')
@section('title', trans('marketplace::messages.gift_codes.title'))
@section('content')
<div class="container content">
 @include('marketplace::_breadcrumbs', ['items' => [['label' => trans('marketplace::messages.gift_codes.title')]]])
 <div class="d-flex align-items-center gap-3 mb-4"><span class="d-inline-flex align-items-center justify-content-center rounded-3 bg-primary text-white fs-3" style="width:3.25rem;height:3.25rem"><i class="bi bi-gift"></i></span><div><h1 class="h2 mb-1">@lang('marketplace::messages.gift_codes.title')</h1><p class="text-muted mb-0">@lang('marketplace::messages.gift_codes.description')</p></div></div>
 @if(session('gift_code'))<div class="alert alert-success"><strong>@lang('marketplace::messages.gift_codes.copy_now')</strong><div class="input-group mt-2"><input class="form-control font-monospace" readonly value="{{ session('gift_code') }}"><button class="btn btn-outline-success" type="button" onclick="navigator.clipboard.writeText(this.previousElementSibling.value)"><i class="bi bi-copy"></i></button></div></div>@endif
 <div class="row g-4"><div class="col-lg-5"><div class="card rounded-4 mb-4"><div class="card-header"><strong>@lang('marketplace::messages.gift_codes.redeem')</strong></div><div class="card-body"><form method="POST" action="{{ route('marketplace.gift-codes.redeem') }}">@csrf<label class="form-label" for="giftCode">@lang('marketplace::messages.gift_codes.code')</label><input id="giftCode" name="code" class="form-control text-uppercase font-monospace @error('code') is-invalid @enderror" maxlength="100" required>@error('code')<span class="invalid-feedback">{{ $message }}</span>@enderror<button class="btn btn-primary w-100 mt-3"><i class="bi bi-gift me-1"></i>@lang('marketplace::messages.gift_codes.redeem_action')</button></form></div></div></div>
 <div class="col-lg-7">@if($paidResources->isNotEmpty())@php($selectedGiftResources = (array) old('resources', []))<div class="card rounded-4 mb-4"><div class="card-header"><strong>@lang('marketplace::messages.gift_codes.create')</strong></div><div class="card-body"><form method="POST" action="{{ route('marketplace.gift-codes.store') }}">@csrf<div class="mb-3"><label class="form-label">@lang('marketplace::messages.gift_codes.resources')</label><div class="d-grid gap-2">@foreach($paidResources as $resource)<label class="form-check border rounded p-3"><input class="form-check-input" type="checkbox" name="resources[]" value="{{ $resource->id }}" @checked(in_array($resource->id,$selectedGiftResources))><span class="ms-1">{{ $resource->name }} · {{ format_money($resource->price) }}</span></label>@endforeach</div>@error('resources')<div class="text-danger small">{{ $message }}</div>@enderror</div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="usageLimit">@lang('marketplace::messages.gift_codes.uses')</label><input id="usageLimit" type="number" name="usage_limit" class="form-control" min="1" max="100000" step="1" value="{{ old('usage_limit',1) }}" required></div><div class="col-md-6"><label class="form-label" for="expiresAt">@lang('marketplace::messages.gift_codes.expires')</label><input id="expiresAt" type="datetime-local" name="expires_at" class="form-control" value="{{ old('expires_at') }}"></div></div><button class="btn btn-primary mt-3">@lang('marketplace::messages.gift_codes.create_action')</button></form></div></div>@endif
 <div class="card rounded-4"><div class="card-header"><strong>@lang('marketplace::messages.gift_codes.mine')</strong></div><div class="list-group list-group-flush">@forelse($codes as $code)<div class="list-group-item p-3"><div class="d-flex justify-content-between"><strong class="font-monospace">{{ $code->code_hint }}</strong><span>{{ $code->redemptions_count }}/{{ $code->usage_limit }}</span></div><div class="small text-muted mt-1">{{ $code->resources->pluck('name')->join(', ') }}</div><div class="small mt-1">{{ $code->expires_at ? format_date($code->expires_at,true) : trans('marketplace::messages.gift_codes.no_expiry') }}</div></div>@empty<div class="list-group-item text-muted p-4 text-center">@lang('marketplace::messages.gift_codes.empty')</div>@endforelse</div></div></div></div>
</div>
@endsection
