<?php
return [
 'title'=>'Marketplace','permissions'=>['admin'=>'Manage marketplace settings','moderate'=>'View, approve and reject pending resources','bypass_moderation'=>'Publish resources without moderation','archive'=>'Archive resources','pause'=>'Pause and resume resources','edit'=>'Edit any resource','delete'=>'Permanently delete any resource','delete_comments'=>'Delete comments and comments by user','reset_ratings'=>'Reset resource ratings','download_paid'=>'Download paid resources without purchasing'],
 'categories'=>['title'=>'Categories','description'=>'Organize your marketplace across :count categories.','list'=>'Marketplace categories','create'=>'Create category','create_help'=>'Define where community resources will be organized.','edit'=>'Edit :category','edit_help'=>'Update the category presentation, access, and availability.','information'=>'General information','access_settings'=>'Access permissions','access'=>'Access','status'=>'Status','actions'=>'Actions','resources'=>'Resources','public'=>'Public','restricted'=>'Restricted','roles'=>':count allowed roles','roles_help'=>'Only selected roles will be able to access this category.','active'=>'Active','disabled'=>'Disabled','empty'=>'No categories yet','empty_help'=>'Create the first category to start organizing resources.','position'=>'Position','position_help'=>'Enter a non-negative whole number. Lower values are displayed first.','slug_help'=>'Used in the public category URL. Letters, numbers, hyphens, and underscores only.','icon_help'=>'Bootstrap Icons class shown next to the category.','premium'=>'Restrict to selected roles (premium)','enabled'=>'Category enabled','enabled_help'=>'Disabled categories are hidden from the public marketplace.','not_empty'=>'A category containing resources cannot be deleted.'],
 'tags'=>['title'=>'Tags','description'=>'Organize marketplace resources with :count reusable tags.','list'=>'Marketplace tags','create'=>'Create tag','create_help'=>'Add a reusable label that authors can assign to their resources.','edit'=>'Edit :tag','edit_help'=>'Update the tag presentation and availability.','information'=>'Tag information','status'=>'Status','actions'=>'Actions','resources'=>'Resources','position'=>'Position','position_help'=>'Enter a non-negative whole number. Lower values are displayed first.','slug_help'=>'Internal identifier for future filtering. Letters, numbers, hyphens, and underscores only.','color'=>'Color','enabled'=>'Tag enabled','enabled_help'=>'Only enabled tags can be selected for resources.','active'=>'Active','disabled'=>'Disabled','empty'=>'No tags yet','empty_help'=>'Create the first tag to improve resource organization.','not_empty'=>'A tag assigned to resources cannot be deleted.'],
 'resource_list'=>['title'=>':category resources','description'=>'Review every resource currently assigned to this category.','list'=>'Resources','open'=>'View resources in :category','name'=>'Resource name','version'=>'Current version','author'=>'Author','status'=>'Status','empty'=>'No resources in this category','empty_help'=>'Resources assigned to this category will appear here.'],
 'pending_resources'=>['title'=>'Pending resources','description'=>'Review resources waiting for moderation before publication.','list'=>'Resources awaiting approval','publication_date'=>'Publication date','empty'=>'No resources awaiting approval','empty_help'=>'New resources requiring moderation will appear here.'],
 'reports'=>['title'=>'Reports','description'=>'Review potentially offensive resources and comments reported by community members.','received'=>'Received reports','content'=>'Reported content','reporter'=>'Reported by','reason'=>'Reason','date'=>'Date','resource'=>'Resource','comment'=>'Comment','view'=>'View resource','removed'=>'Content removed','empty'=>'No reports received','empty_help'=>'New community reports will appear here.'],
 'stats'=>['published'=>'Published resources','pending'=>'Resources awaiting approval','spent'=>'Points spent on resources'],
 'moderation'=>['title'=>'Moderation','approve'=>'Approve','reject'=>'Reject','reason'=>'Rejection reason','empty'=>'There are no pending resources.','approved'=>'Resource approved.','rejected'=>'Resource rejected.'],
 'rate_limits'=>['title'=>'Action rate limits','help'=>'Set the minimum waiting time between attempts by the same user.','disabled_help'=>'Set any value to 0 to disable that action limit completely. The maximum configurable wait is 86,400 seconds (24 hours).','seconds'=>'seconds','publish'=>'Publish resources','publish_help'=>'Waiting time before the user can submit another new resource.','edit'=>'Edit resources','edit_help'=>'Waiting time before the user can edit resource content again.','update'=>'Publish resource updates','update_help'=>'Waiting time before the user can publish another version or changelog.','comment'=>'Post comments','comment_help'=>'Waiting time before the user can post another comment.'],
 'settings'=>['title'=>'Settings','description'=>'Control publishing, community interactions, and resource file limits.','general'=>'Publishing and interactions','files'=>'Files','moderation'=>'Require approval before publishing','moderation_help'=>'New resources must be reviewed unless the author can bypass moderation.','pause_submissions'=>'Pause new resource submissions','pause_submissions_help'=>'Users cannot create new resources. Existing resources can still be edited and updated.','pause_comments'=>'Pause resource comments','pause_comments_help'=>'Prevents all users from posting new comments without removing existing ones.','require_login_for_free_downloads'=>'Require login for free downloads','require_login_for_free_downloads_help'=>'Guests will be asked to sign in before downloading a free resource or continuing to its external website.','max_file_size'=>'Maximum file size','max_file_size_help'=>'Maximum allowed size for resource files, expressed in kilobytes.','max_editor_image_size'=>'Maximum editor image size','max_editor_image_size_help'=>'Maximum size of each JPG, PNG, or WebP uploaded through TinyMCE.','max_editor_images'=>'Images per resource','max_editor_images_help'=>'Maximum number of Marketplace-hosted images allowed in one resource description.','allowed_extensions'=>'Allowed file extensions','allowed_extensions_help'=>'Comma, space, or line-separated whitelist. Files without an allowed extension are rejected.','blocked_extensions'=>'These dangerous extensions are always blocked and cannot be added to the whitelist.','allowed_extensions_required'=>'Add at least one allowed extension.','allowed_extensions_invalid'=>'These extensions have an invalid format: :extensions.','allowed_extensions_forbidden'=>'These extensions are permanently forbidden: :extensions.'],
];
