<?php
return [
 'title'=>'Marketplace','permissions'=>['admin'=>'Manage marketplace settings','moderate'=>'View, approve and reject pending resources','bypass_moderation'=>'Publish resources without moderation','archive'=>'Archive resources','pause'=>'Pause and resume resources','edit'=>'Edit any resource','delete'=>'Permanently delete any resource','delete_comments'=>'Delete comments and comments by user','reset_ratings'=>'Reset resource ratings','download_paid'=>'Download paid resources without purchasing'],
 'categories'=>['title'=>'Categories','description'=>'Organize your marketplace across :count categories.','list'=>'Marketplace categories','create'=>'Create category','create_help'=>'Define where community resources will be organized.','edit'=>'Edit :category','edit_help'=>'Update the category presentation, access, and availability.','information'=>'General information','access_settings'=>'Access permissions','access'=>'Access','status'=>'Status','actions'=>'Actions','resources'=>'Resources','public'=>'Public','restricted'=>'Restricted','roles'=>':count allowed roles','roles_help'=>'Only selected roles will be able to access this category.','active'=>'Active','disabled'=>'Disabled','empty'=>'No categories yet','empty_help'=>'Create the first category to start organizing resources.','position'=>'Position','position_help'=>'Enter a non-negative whole number. Lower values are displayed first.','slug_help'=>'Used in the public category URL. Letters, numbers, hyphens, and underscores only.','icon_help'=>'Bootstrap Icons class shown next to the category.','premium'=>'Restrict to selected roles (premium)','enabled'=>'Category enabled','enabled_help'=>'Disabled categories are hidden from the public marketplace.','not_empty'=>'A category containing resources cannot be deleted.'],
 'resource_list'=>['title'=>':category resources','description'=>'Review every resource currently assigned to this category.','list'=>'Resources','open'=>'View resources in :category','name'=>'Resource name','version'=>'Current version','author'=>'Author','status'=>'Status','empty'=>'No resources in this category','empty_help'=>'Resources assigned to this category will appear here.'],
 'stats'=>['published'=>'Published resources','pending'=>'Resources awaiting approval','spent'=>'Points spent on resources'],
 'moderation'=>['title'=>'Moderation','approve'=>'Approve','reject'=>'Reject','reason'=>'Rejection reason','empty'=>'There are no pending resources.','approved'=>'Resource approved.','rejected'=>'Resource rejected.'],
 'settings'=>['title'=>'Settings','description'=>'Control publishing, community interactions, and resource file limits.','general'=>'Publishing and interactions','files'=>'Files','moderation'=>'Require approval before publishing','moderation_help'=>'New resources must be reviewed unless the author can bypass moderation.','pause_submissions'=>'Pause new resource submissions','pause_submissions_help'=>'Users cannot create new resources. Existing resources can still be edited and updated.','pause_comments'=>'Pause resource comments','pause_comments_help'=>'Prevents all users from posting new comments without removing existing ones.','max_file_size'=>'Maximum file size','max_file_size_help'=>'Maximum allowed size for resource files, expressed in kilobytes.'],
];
