<?php
return [
 'title'=>'Marketplace','subtitle'=>'Discover and share resources with the community.','submit'=>'Submit resource','all_categories'=>'All categories','search'=>'Search resources...','empty'=>'No resources are available.','free'=>'Free','by'=>'By','saved'=>'The resource was saved successfully.','already_unlocked'=>'You already have access to this resource.','insufficient_money'=>'You do not have enough coins.','purchased'=>'Resource unlocked successfully.','comment_added'=>'Comment posted.','rating_saved'=>'Rating saved.','comments'=>'Comments','comment'=>'Comment','no_comments'=>'There are no comments yet.','downloads'=>'downloads','get_resource'=>'Get resource','rate'=>'Rate','unlock'=>'Unlock','file'=>'Downloadable file','external'=>'External link',
 'fields'=>['category'=>'Category','version'=>'Version','summary'=>'Summary','description'=>'Description','delivery'=>'Delivery type','price'=>'Coin price','file'=>'File','url'=>'External URL'],
 'status'=>['pending'=>'This resource is awaiting approval.','published'=>'Published','rejected'=>'This resource was rejected.'],
 'status_labels'=>['pending'=>'Pending','published'=>'Published','rejected'=>'Rejected'],
 'paused'=>'Paused','pause_notice'=>'This resource is paused. Downloads, purchases, comments and ratings are temporarily disabled.',
 'notifications'=>['comment'=>':user commented on your resource ":resource".','approved'=>'Your resource ":resource" was approved.','rejected'=>'Your resource ":resource" was rejected. Reason: :reason'],
 'external_warning'=>['title'=>'You are leaving this site','message'=>'This resource is hosted on an external website. Marketplace does not control the content or security of the destination page.','destination'=>'You will be redirected to:','continue'=>'Continue to external site','cancel'=>'Stay and return to resource'],
 'moderation'=>['index_notice'=>'Moderation mode: published, pending and rejected resources are displayed.','review'=>'Review pending resource','approve'=>'Approve','reject'=>'Reject','reason'=>'Required rejection reason','approved'=>'The resource was approved.','rejected'=>'The resource was rejected.','tools'=>'Moderation tools','archive'=>'Archive resource','archived'=>'The resource was archived and is now completely hidden.','pause'=>'Pause resource','paused'=>'The resource was paused.','resume'=>'Resume resource','resumed'=>'The resource was resumed.','reset_ratings'=>'Reset ratings','ratings_reset'=>'The resource ratings were reset.','delete_resource'=>'Delete permanently','delete_comment'=>'Delete','delete_user_comments'=>'Delete all by user','user_comments_deleted'=>':count comments by :user were deleted.'],
 'confirm'=>['archive'=>'Archive this resource? It will be completely hidden, including from its author.','delete_resource'=>'Permanently delete this resource and all its data? This action cannot be undone.','reset_ratings'=>'Reset all ratings for this resource?','delete_comment'=>'Delete this comment?','delete_user_comments'=>'Delete every comment by :user across all resources?'],
 'editor'=>['help'=>'You can use headings, lists, links, external images, tables and other formatting. Unsafe content is removed automatically.'],
];
