@csrf
<div class="mb-3"><label class="form-label">@lang('marketplace::messages.fields.category')</label><select name="category_id" class="form-select" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$resource->category_id??null)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div class="row"><div class="col-md-8 mb-3"><label class="form-label">@lang('messages.fields.name')</label><input class="form-control" name="name" maxlength="100" value="{{ old('name',$resource->name??'') }}" required></div><div class="col-md-4 mb-3"><label class="form-label">@lang('marketplace::messages.fields.version')</label><input class="form-control" name="version" value="{{ old('version',$resource->version??'') }}"></div></div>
<div class="mb-3"><label class="form-label">@lang('marketplace::messages.fields.summary')</label><textarea class="form-control" name="summary" maxlength="500" required>{{ old('summary',$resource->summary??'') }}</textarea></div>
<div class="mb-3"><label class="form-label">@lang('marketplace::messages.fields.description')</label><textarea class="form-control" rows="10" name="description" required>{{ old('description',$resource->description??'') }}</textarea></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">@lang('marketplace::messages.fields.delivery')</label><select id="deliveryType" name="delivery_type" class="form-select"><option value="file" @selected(old('delivery_type',$resource->delivery_type??'file')==='file')>@lang('marketplace::messages.file')</option><option value="external" @selected(old('delivery_type',$resource->delivery_type??'')==='external')>@lang('marketplace::messages.external')</option></select></div><div class="col-md-6 mb-3"><label class="form-label">@lang('marketplace::messages.fields.price')</label><input type="number" step="0.01" min="0" name="price" class="form-control" value="{{ old('price',$resource->price??0) }}" required></div></div>
<div class="mb-3"><label class="form-label">@lang('marketplace::messages.fields.file')</label><input type="file" name="file" class="form-control"></div><div class="mb-3"><label class="form-label">@lang('marketplace::messages.fields.url')</label><input type="url" name="external_url" class="form-control" value="{{ old('external_url',$resource->external_url??'') }}"></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<button class="btn btn-primary">@lang('messages.actions.save')</button>
