@extends('layouts.app')
@section('title',$resource->name)
@section('content')
<div class="container content"><div class="row"><main class="col-lg-8"><div class="d-flex justify-content-between"><div><span class="badge bg-secondary">{{ $resource->category->name }}</span><h1 class="mt-2">{{ $resource->name }}</h1><p class="text-muted">@lang('marketplace::messages.by') {{ $resource->author->name }} @if($resource->version) · v{{ $resource->version }} @endif</p></div>@if($resource->isOwnedBy(auth()->user()))<a href="{{ route('marketplace.resources.edit',$resource) }}" class="btn btn-outline-secondary align-self-start">@lang('messages.actions.edit')</a>@endif</div>
 @if($resource->status!=='published')<div class="alert alert-warning">@lang('marketplace::messages.status.'.$resource->status) @if($resource->moderation_note)<hr>{{ $resource->moderation_note }}@endif</div>@endif
 <div class="card mb-4"><div class="card-body"><p class="lead">{{ $resource->summary }}</p><div style="white-space:pre-wrap">{{ $resource->description }}</div></div></div>
 <h2 class="h4">@lang('marketplace::messages.comments')</h2>@auth @if($resource->isUnlockedBy(auth()->user())&&$resource->status==='published')<form method="POST" action="{{ route('marketplace.comments.store',$resource) }}" class="mb-4">@csrf<textarea name="content" class="form-control mb-2" rows="3" required></textarea><button class="btn btn-primary">@lang('marketplace::messages.comment')</button></form>@endif @endauth
 @forelse($resource->comments as $comment)<div class="card mb-2"><div class="card-body"><strong>{{ $comment->user->name }}</strong><small class="text-muted ms-2">{{ format_date($comment->created_at,true) }}</small><p class="mb-0 mt-2">{{ $comment->content }}</p></div></div>@empty<p class="text-muted">@lang('marketplace::messages.no_comments')</p>@endforelse</main>
 <aside class="col-lg-4"><div class="card"><div class="card-body text-center"><div class="display-6">{{ $resource->price>0?format_money($resource->price):trans('marketplace::messages.free') }}</div><p>★ {{ $resource->averageRating() }} · {{ $resource->downloads }} @lang('marketplace::messages.downloads')</p>@auth @if($resource->isUnlockedBy(auth()->user()))<a class="btn btn-success w-100 mb-3" href="{{ route('marketplace.resources.download',$resource) }}">@lang('marketplace::messages.get_resource')</a><form method="POST" action="{{ route('marketplace.ratings.store',$resource) }}">@csrf<div class="input-group"><select name="rating" class="form-select">@for($i=5;$i>=1;$i--)<option value="{{ $i }}">{{ $i }} ★</option>@endfor</select><button class="btn btn-outline-primary">@lang('marketplace::messages.rate')</button></div></form>@elseif($resource->status==='published')<form method="POST" action="{{ route('marketplace.resources.purchase',$resource) }}">@csrf<button class="btn btn-primary w-100">@lang('marketplace::messages.unlock')</button></form>@endif @else<a href="{{ route('login') }}" class="btn btn-primary w-100">@lang('auth.login')</a>@endauth</div></div></aside></div></div>
@endsection
