<?php
return [
 'title'=>'Marketplace','permissions'=>['admin'=>'Administrar la configuración del marketplace','moderate'=>'Ver, aprobar y rechazar recursos pendientes','bypass_moderation'=>'Publicar recursos sin pasar por moderación','archive'=>'Archivar recursos','pause'=>'Pausar y reanudar recursos','edit'=>'Editar cualquier recurso','delete'=>'Eliminar permanentemente cualquier recurso','delete_comments'=>'Eliminar comentarios y comentarios por usuario','reset_ratings'=>'Reiniciar las valoraciones de recursos','download_paid'=>'Descargar recursos de pago sin comprarlos'],
 'categories'=>['title'=>'Categorías','description'=>'Organiza el marketplace en :count categorías.','list'=>'Categorías del marketplace','create'=>'Crear categoría','create_help'=>'Define dónde se organizarán los resources de la comunidad.','edit'=>'Editar :category','edit_help'=>'Actualiza la presentación, el acceso y la disponibilidad de la categoría.','information'=>'Información general','access_settings'=>'Permisos de acceso','access'=>'Acceso','status'=>'Estado','actions'=>'Acciones','resources'=>'Resources','public'=>'Pública','restricted'=>'Restringida','roles'=>':count roles permitidos','roles_help'=>'Solo los roles seleccionados podrán acceder a esta categoría.','active'=>'Activa','disabled'=>'Deshabilitada','empty'=>'Todavía no hay categorías','empty_help'=>'Crea la primera categoría para comenzar a organizar los resources.','position'=>'Posición','position_help'=>'Ingresa un número entero no negativo. Los valores menores se muestran primero.','slug_help'=>'Se utiliza en la URL pública. Solo admite letras, números, guiones y guiones bajos.','icon_help'=>'Clase de Bootstrap Icons mostrada junto a la categoría.','premium'=>'Restringir a roles seleccionados (premium)','enabled'=>'Categoría habilitada','enabled_help'=>'Las categorías deshabilitadas se ocultan del marketplace público.','not_empty'=>'No se puede eliminar una categoría que contiene resources.'],
 'resource_list'=>['title'=>'Resources de :category','description'=>'Consulta todos los resources asignados actualmente a esta categoría.','list'=>'Resources','open'=>'Ver resources de :category','name'=>'Nombre del resource','version'=>'Versión actual','author'=>'Autor','status'=>'Estado','empty'=>'No hay resources en esta categoría','empty_help'=>'Los resources asignados a esta categoría aparecerán aquí.'],
 'stats'=>['published'=>'Resources publicados','pending'=>'Resources pendientes de aprobación','spent'=>'Puntos gastados en resources'],
 'moderation'=>['title'=>'Moderación','approve'=>'Aprobar','reject'=>'Rechazar','reason'=>'Motivo del rechazo','empty'=>'No hay recursos pendientes.','approved'=>'Recurso aprobado.','rejected'=>'Recurso rechazado.'],
 'settings'=>['title'=>'Configuración','description'=>'Controla la publicación, las interacciones de la comunidad y los límites de archivos.','general'=>'Publicación e interacciones','files'=>'Archivos','moderation'=>'Requerir aprobación antes de publicar','moderation_help'=>'Los nuevos resources deben revisarse, salvo que el autor pueda omitir la moderación.','pause_submissions'=>'Pausar publicación de resources','pause_submissions_help'=>'Los usuarios no podrán crear nuevos resources. Los existentes podrán editarse y actualizarse.','pause_comments'=>'Pausar comentarios','pause_comments_help'=>'Impide que todos los usuarios publiquen comentarios nuevos sin eliminar los existentes.','max_file_size'=>'Tamaño máximo por archivo','max_file_size_help'=>'Tamaño máximo permitido para los archivos de resources, expresado en kilobytes.'],
];
