<?php
return [
 'title'=>'Marketplace','subtitle'=>'Descubre y comparte recursos con la comunidad.','submit'=>'Publicar recurso','all_categories'=>'Todas las categorías','search'=>'Buscar recursos...','empty'=>'No hay recursos disponibles.','free'=>'Gratis','by'=>'Por','saved'=>'El recurso se guardó correctamente.','already_unlocked'=>'Ya tienes acceso a este recurso.','insufficient_money'=>'No tienes suficientes monedas.','purchased'=>'Recurso desbloqueado correctamente.','comment_added'=>'Comentario publicado.','rating_saved'=>'Valoración guardada.','comments'=>'Comentarios','comment'=>'Comentar','no_comments'=>'Todavía no hay comentarios.','downloads'=>'descargas','get_resource'=>'Obtener recurso','rate'=>'Valorar','unlock'=>'Desbloquear','file'=>'Archivo descargable','external'=>'Enlace externo',
 'fields'=>['category'=>'Categoría','version'=>'Versión','summary'=>'Resumen','description'=>'Descripción','banner'=>'Banner del recurso','delivery'=>'Tipo de entrega','price'=>'Precio en monedas','file'=>'Archivo','url'=>'URL externa'],
 'status'=>['pending'=>'Este recurso está esperando aprobación.','published'=>'Publicado','rejected'=>'Este recurso fue rechazado.'],
 'status_labels'=>['pending'=>'Pendiente','published'=>'Publicado','rejected'=>'Rechazado'],
 'paused'=>'Pausado','pause_notice'=>'Este recurso está pausado. Las descargas, compras, comentarios y valoraciones están temporalmente deshabilitados.',
 'notifications'=>['comment'=>':user comentó en tu recurso ":resource".','approved'=>'Tu recurso ":resource" fue aprobado.','rejected'=>'Tu recurso ":resource" fue rechazado. Motivo: :reason'],
 'external_warning'=>['title'=>'Estás abandonando el sitio','message'=>'Este recurso se encuentra alojado en un sitio externo. Marketplace no controla el contenido ni la seguridad de la página de destino.','destination'=>'Serás dirigido a:','continue'=>'Continuar al sitio externo','cancel'=>'No ir y volver al recurso'],
 'moderation'=>['index_notice'=>'Modo de moderación: se muestran los recursos publicados, pendientes y rechazados.','review'=>'Revisar recurso pendiente','approve'=>'Aprobar','reject'=>'Rechazar','reason'=>'Razón obligatoria del rechazo','approved'=>'El recurso fue aprobado.','rejected'=>'El recurso fue rechazado.','tools'=>'Herramientas de moderación','archive'=>'Archivar recurso','archived'=>'El recurso fue archivado y ahora está completamente oculto.','pause'=>'Pausar recurso','paused'=>'El recurso fue pausado.','resume'=>'Reanudar recurso','resumed'=>'El recurso fue reanudado.','reset_ratings'=>'Reiniciar valoraciones','ratings_reset'=>'Las valoraciones del recurso fueron reiniciadas.','delete_resource'=>'Eliminar permanentemente','delete_comment'=>'Eliminar','delete_user_comments'=>'Eliminar todos los suyos','user_comments_deleted'=>'Se eliminaron :count comentarios de :user.'],
 'confirm'=>['archive'=>'¿Archivar este recurso? Quedará completamente oculto, incluso para su autor.','delete_resource'=>'¿Eliminar permanentemente este recurso y todos sus datos? Esta acción no se puede deshacer.','reset_ratings'=>'¿Reiniciar todas las valoraciones de este recurso?','delete_comment'=>'¿Eliminar este comentario?','delete_user_comments'=>'¿Eliminar todos los comentarios de :user en todos los recursos?'],
 'editor'=>['help'=>'Puedes usar encabezados, listas, enlaces, imágenes externas, tablas y otros formatos. El contenido peligroso se eliminará automáticamente.'],
 'banner'=>['help'=>'Imagen opcional JPG, PNG o WebP. Máximo 5 MB y 4096 × 4096 píxeles.','remove'=>'Eliminar el banner actual'],
 'updates'=>['title'=>'Historial de versiones','publish'=>'Publicar una nueva versión','version'=>'Nueva versión','changelog'=>'Cambios de esta versión','file'=>'Archivo actualizado','url'=>'Enlace actualizado','publish_action'=>'Publicar actualización','published'=>'La nueva versión fue publicada correctamente.','updated'=>'Actualizado','last_update'=>'Última actualización:','by'=>'Publicado por :user','empty'=>'Este recurso todavía no tiene actualizaciones.'],
 'sort'=>['label'=>'Ordenar recursos','updated'=>'Actualizados recientemente','downloads'=>'Mayor número de descargas','rating'=>'Mejor valoración','apply'=>'Filtrar'],
];
